/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-26 06:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.Sale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import fixnimartjava.appweb.utils.Utilidad;

public final class create_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("fixnimartjava.appweb.utils.Utilidad");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("    <head>        \n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Views/Shared/title.jsp", out, false);
      out.write("\n");
      out.write("        <title>Crear Venta</title>\n");
      out.write("    </head>\n");
      out.write("    <style>\n");
      out.write("        tfoot tr td {\n");
      out.write("            padding: 0 !important;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <body>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Views/Shared/headerBody.jsp", out, false);
      out.write("  \n");
      out.write("        <main class=\"container mt-5\">\n");
      out.write("            <div style=\"color:red;\" id=\"error\"></div>\n");
      out.write("            <form id=\"saleForm\" action=\"Sale\" method=\"post\" autocomplete=\"on\">\n");
      out.write("                <div id=\"errorList\"></div>\n");
      out.write("                <input type=\"hidden\" name=\"accion\" value=\"");
      out.print(request.getAttribute("accion"));
      out.write("\">\n");
      out.write("                <div class=\"input-field \">\n");
      out.write("                    <input  id=\"txtName\" placeholder=\"Nombre del cliente\" type=\"text\" name=\"clientName\" required class=\"validate\" maxlength=\"30\">\n");
      out.write("                    <label for=\"txtName\"></label>\n");
      out.write("                </div>     \n");
      out.write("                <div>\n");
      out.write("                    <input id=\"fechaVenta\" type=\"datetime-local\" name=\"dateOfSale\" required class=\"validate input-datetimeNow\">\n");
      out.write("                    <label for=\"fechaVenta\">Fecha de venta</label>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"txtCodigo\">Código:</label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"txtCodigo\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>Tipo de factura</label>\n");
      out.write("                    <select onchange=\"typeInvoice(this)\" id=\"invoiceType\" class=\"browser-default\">\n");
      out.write("                        <option value=\"consumidorFinal\">Consumidor final</option>\n");
      out.write("                        <option value=\"creditoFiscal\">Credito fiscal</option>\n");
      out.write("                    </select>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"txtNRC\" name=\"nrc\" value=\"\" disabled=\"\" hidden=\"\" title=\"NRC\" placeholder=\"NRC. Eje: 123456789\" required=\"\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <input id=\"productCount\" type='hidden' name='productCount' value=\"-1\">\n");
      out.write("                <table class=\"table table-striped table-hover\">\n");
      out.write("                    <thead> \n");
      out.write("                        <tr>\n");
      out.write("                            <th>Nombre</th>\n");
      out.write("                            <th>Descripción</th>\n");
      out.write("                            <th>Cantidad</th>\n");
      out.write("                            <th>Precio U</th>\n");
      out.write("                            <th>SubTotal</th>\n");
      out.write("                            <th>Acciones</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody id=\"tbody\">\n");
      out.write("                    <td colspan=\"5\" id=\"loadingData\" hidden=\"\">\n");
      out.write("                        <div class=\"progress\" role=\"status\">\n");
      out.write("                            <div class=\"indeterminate\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- Aquí se agregarán los productos dinámicamente -->\n");
      out.write("                    </tbody>\n");
      out.write("                    <tfoot>\n");
      out.write("                        <tr hidden=\"\" id=\"trIva\">\n");
      out.write("                            <td colspan=\"3\"></td>\n");
      out.write("                            <th>Iva:</th>\n");
      out.write("                            <td><input title=\"iva\" id=\"iva\" name=\"iva\" value=\"0.00\" max=\"1.13\" min=\"1.13\" required=\"\" readonly style=\"width: 75px;\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr hidden=\"\" id=\"trSum\">\n");
      out.write("                            <td colspan=\"3\"></td>\n");
      out.write("                            <th>Suma:</th>\n");
      out.write("                            <td><input id=\"sum\" name=\"sum\" value=\"0.00\" readonly style=\"width: 75px;\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td colspan=\"3\"></td>\n");
      out.write("                            <th>Total:</th>\n");
      out.write("                            <td><input id=\"total\" name=\"totalSale\" value=\"0.00\" readonly style=\"width: 75px;\"/></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tfoot>\n");
      out.write("                </table>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" id=\"ticket\"disabled>Generar Factura</button>\n");
      out.write("                <a class=\"btn btn-info\" href=\"Product\">Ver Productos</a>\n");
      out.write("            </form>\n");
      out.write("        </main>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/Views/Shared/footerBody.jsp", out, false);
      out.write("\n");
      out.write("        <script src=\"");
      out.print(Utilidad.obtenerRuta(request, "/wwwroot/js/createSale.js"));
      out.write("\"></script>\n");
      out.write("        <script>\n");
      out.write("                        var nrc = document.querySelector(\"#txtNRC\");\n");
      out.write("                        var isTaxCredit = false;\n");
      out.write("                        function typeInvoice(e) {\n");
      out.write("                            if (e.value === \"creditoFiscal\") {\n");
      out.write("                                isTaxCredit = true;\n");
      out.write("                                trIva.hidden = false;\n");
      out.write("                                trSum.hidden = false;\n");
      out.write("                                nrc.hidden = false;\n");
      out.write("                                nrc.disabled = false;\n");
      out.write("//                                document.querySelector(\"#iva\").value = iva;\n");
      out.write("\n");
      out.write("                            } else {\n");
      out.write("                                isTaxCredit = false;\n");
      out.write("                                trIva.hidden = true;\n");
      out.write("                                trSum.hidden = true;\n");
      out.write("                                nrc.hidden = true;\n");
      out.write("                                nrc.disabled = true;\n");
      out.write("                                document.querySelector(\"#iva\").value = 0.00;\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("        </script>\n");
      out.write("    </body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
